### ISSUE TITLE
Game "freezes" partially

### ISSUE THREAD

**Issue by Chrisu88** [KnuckleCracker/CW4-bug-tracker#420] opened 2020-12-09 07:29 UTC
Hi, I have a weired issue in one save game where most friendly and and enemy units seems to be on pause, while the creepers still moves. Some of my units still shoot until they run out of ammo because the packages are frozen in transit.
The timers of launchers and skimmer factory are stopped but Stashes still doing their thing.

Attached: savegame & output log

[gamefreeze.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5664156/gamefreeze.zip)

**Comment by Karsten75** [comment] 2020-12-09 16:10
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5667146/output_log.txt)

The log file you supplied did not have the error. Fortunatley, the save file allowed me to recreate the error and it appears in the attached log file. 

Your save file will not be usable, even after the issue is resolved, unfortunately.

**Comment by knucracker** [comment] 2020-12-09 18:05
That's caused by a blob walking out of the map and will be fixed in the 1.0.1 update coming soon (within days hopefully). I added checks so that the save should actually work in 1.0.1. It usually doesn't work that way, but I was able to make it work for this problem

**Closed by knucracker** 2020-12-09 18:05 UTC
Labels: 1.0.1, bug
