### ISSUE TITLE
Stutter every few seconds

### ISSUE THREAD

**Issue by bilbohob** [KnuckleCracker/CW4-bug-tracker#354] opened 2020-12-04 09:53 UTC
Hello,

I experience stutters every few second when the game is running (in a map with the game not paused)

I have a good config : 
CPU I7-9700K @ 3.600 GHz 8 CPU
GeForce RTX 2060 6go VRAM
16 GO RAM

The game is not umplayable but it is very frustationg.

Thank you very much.
[DxDiag.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5641888/DxDiag.txt)

**Comment by knucracker** [comment] 2020-12-04 18:48
So when the game is paused, there is no stutter. When the game it running, that's the only time you see the stutter?  How would you characterize the stutter? Is is a long pause, a barely noticeable pause, etc.
In your dxdiag I see you are running on a 4k monitor at 60hz. Is the game set to run at 4k or do you have it at a lower resolution? Also is the game in a window or fullscreen?

Try varios combinations of window, lower res, etc. and see if that affected the stutter. Let me know what you find...

**Comment by Karsten75** [comment] 2020-12-04 19:33
I messed up earlier when adding the "duplicate tag" 

This seems a duplicate of the issues in #350 after the earlier issues in that thread were resolved

**Comment by bilbohob** [comment] 2020-12-05 10:49
Hello,

The stutter is regular and last for one second. It's more like a frame drop than a freeze.
The frame drop doesn't register with the steam FPS counter.
I tried changing the resolution to lower and reducing the graphics quality but nothing helps.
I also tried in windowed and in full-screen but it doesn't help either.

Thank you for your time, I continued the game and it's great :)

**Comment by Karsten75** [comment] 2020-12-05 23:23
We recently had more reports of "stuttering. In one case, there was associated high power use (200W) from the GPU. The user had a large number (<200) chrome tabs.

They updated their driver and rebooted to clean things out. That resolved their issue and power consumption dropped to approx 40W.

If you can perhaps take a video (with your phone) that demonstrates the stuttering.

Also, please try this. Zoom in as close as you can, move the camera as far left as it can go. Using arorw keys, navigate as far left as you can go. Do you see the stuttering then?

Again, if you do, please attempt to take a video and upload that.

**Comment by bilbohob** [comment] 2020-12-06 11:14
Hello,

I'm sorry but my phone is not powerful enough to capture the frame change.
I captured it with NVIDIA overlay.

Beside the occasional stuttering of the capture you can see it clearly at the middle of the video. It does it even when paused.

I exited Mozilla (with 4-5 tabs) and all others apps but it didn't change anything.

The video.
https://drive.google.com/file/d/1RFr3TwubqAIytlBzOTC-N_-Q3y6nEDFJ/view?usp=sharing

Thank you.

**Comment by Karsten75** [comment] 2020-12-06 16:36
Might well be the overlays? We have not been able to recreate any stutter on any machine we have access to.

**Comment by bilbohob** [comment] 2020-12-07 07:07
I have tried disabling the steam and Nvidia overlay. I also disabled f.lux and put the game in 1920*1080 but nothing is working.
My drivers are updated. I also put the nvidia 3d settings at default, it didn't help.

Thank you.

**Comment by Karsten75** [comment] 2020-12-07 16:02
I am out of ideas, I will ask @knucracker  to take another look before we close this as something we can't recreate and have insufficient supporting material to attempt a resolution.

**Comment by ZoidtheVoid** [comment] 2020-12-07 21:40
I have exactly the same issue. Game stutters every 3 seconds, no matter what quality settings/resolution I use. It also happens while paused. I've closed every other program, no overlays, using the gog version.
GPU drivers are up to date. 
CPU: Ryzen 3600x
GPU: Nvidia 1080
16 GB RAM

**Comment by knucracker** [comment] 2020-12-07 23:26
Is game mode on?  Try turning it either on or off depending on your current state and see if that makes a difference.
Click the start menu, then the settings gear, then Game Mode.
This is one reference article regarding game mode: https://www.techradar.com/news/windows-10-users-should-turn-this-feature-off-now-for-better-gaming-performance

**Comment by ZoidtheVoid** [comment] 2020-12-07 23:51
No, game mode is disabled. Enabling it did no difference.

**Comment by knucracker** [comment] 2020-12-07 23:54
And the stutter is a long stutter. The earlier reporter mention a stutter that would last 1 second. Is that the case for you as well? or is it more of a quicker thing (a jitter, etc.)  You mentioned the stutter was regardless of settings/resolution. Is that also true for full screen vs window? Also, does the length of the stutter change if the window is small, the game is paused, etc. And lastly, is you system a 4k system, multi monitors, etc?

**Comment by ZoidtheVoid** [comment] 2020-12-08 00:05
The stutter lasts for roughly half a second at a 3 second interval.
It happens both in windowed and fullscreen regardless of the resolution/window size and it always stays the same; half a second every 3 seconds. It also happens while the game is paused. No matter what's being displayed in the game or what settings I use, it always stays the same.
I'm using a dual monitor setup with a 1440p and a 1080p monitor.

**Comment by knucracker** [comment] 2020-12-08 00:22
Does it happen on the main menu? If you watch the planets rotate, do they stop,etc.  Also, this is a big ask I know, but does it happen if you only have one monitor on/connected?  A few people have mentioned the stutter problem, but most folks don't seem to have it. I've not been able to repro it, and none of the beta testers did either. Looking around at "stutter" issues for other games most seem to be centered around nvidia (but not all). I'm running nvidia on my main desktop, though, but don't have any stutter. So I'm looking for what might be 'different' or unique. For what it's worth, I have two monitors as well. Both are 60HZ (a 1440 and a 1080 like you).

**Comment by ZoidtheVoid** [comment] 2020-12-08 00:35
No, it doesn't happen in the main menu.
And yes, it still happens with only a single monitor connected to the GPU.
I've just realized that this stutter only happens when moving the camera. I'm not even sure if it's the game that's stuttering, or just the camera. The game runs perfectly smooth as long as I don't move the camera.

**Comment by knucracker** [comment] 2020-12-08 01:06
That's an interesting observation.  Do you move the camera with the mouse or keyboard? (And have you remapped any keys).  And there is camera panning (right left up down) and then there is map zooming. There is also free cam (press shift-f by default).  See if  you can draw any observations about any of these options

**Comment by ZoidtheVoid** [comment] 2020-12-08 01:33
I've used the free camera to validate my previous statement about the camera, and the stutters are definitely noticable while close up and they happen even if the camera is stationary. The "standard" camera distance is simply too far away for me to notice any stutters in the animations without moving the camera, so I can't say much about that. 
So my previous statement about the camera being involved was wrong, I simply didn't test it thoroughly enough.
If there's anything else I can try out please let me know.

**Comment by bilbohob** [comment] 2020-12-08 08:17
I have tested the same things as ZoidtheVoid and found the same problems.
I am at your disposal for any additional information.
For information my screen setup is 4k for main screen and 1080p for second screen.

**Comment by knucracker** [comment] 2020-12-08 14:42
Ok, so no mouse of movement necessary.  Try this: Create a new map using the map editor. Average size is fine. It will come up as a flat blank map. Land the Rift Lab in the middle of the map and zoom in a bit so you can see the spot light rotate around at the top of the rift lab. Unpause and just let the game run. Don't move or pan the map. Watch the spotlight rotate and see if that stutters every 3 seconds.

If it does, then go to the settings performance tab and uncheck "High FPS" and then come back and watch the spotlight for 30 seconds or so. If that doesn't make a difference, then turn High FPS back on.

Try moving the Rift lab to a corner of the map then pan the map so that you don't see much of the map, but you can still see the rift lab. Zoom in so most of the map is not visible. See if that affects the stutter of the rotating light.

Then take a look at system performance. Bring up the task manager and watch processes and GPU usage to see if you can determine if there is a periodic spike by anything.  If you have TechPowerUp GPU-Z installed, bring that up and watch GPU load to see if there is a spike by anything. On the sensors tab of GPUZ there is a setting button in the top right. In settings there is a sensors tab that has a way to increase the refresh rate.  There is also a "log to file" toggle on GPUZ (bottom left of the sensors tab) that will allow you to log the readings to a file (just uncheck to stop logging).

I'm looking for 'something' that could possibly cause a stutter. The game itself, on a blank map doesn't really do much (especially when paused).

**Comment by Bob2Chiv** [comment] 2020-12-08 16:46
one user (perhaps one of the people on this tracker) reported the following in Discord:
"Looks like it was iCue somehow causing my stutters... Quit the app and now it's running just fine... "

**Comment by ZoidtheVoid** [comment] 2020-12-08 18:09
I followed your instructions, but like I said before, I find it very difficult to notice any stutters in the animations because of the camera distance. I attached 2 logs to this post; both of them are on a blank map with average size with the Rift Lab in the middle of map. Camera was zoomed in to the maximum, with the Rift Lab in the center. 
[60 fpsGPU-Z Sensor Log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5660943/60.fpsGPU-Z.Sensor.Log.txt)
[30fpsGPU-Z Sensor Log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5660944/30fpsGPU-Z.Sensor.Log.txt)

**Closed** 2020-12-08 22:44 UTC
Labels: bug, duplicate
