### ISSUE TITLE
[Bug] Behaviour of PS/2 keyboard connected with USB adaptor is erratic

### ISSUE THREAD

**Issue by DeSangre** [KnuckleCracker/CW4-bug-tracker#4] opened 2020-06-25 16:20 UTC
When using a PS/2 keyboard connected through a USB adaptor the keyboard behaves strangely. For example, it's hard to lock it into diagonals (e.g. you press diagonal down, and it only goes down).

Everything seems to be working normally on the very same computer when using a natively USB keyboard.

**Comment by Karsten75** [comment] 2020-06-27 16:30
This issue cannot be recreated on any keyboard tested with. In fact original submitter could not reproduce on different keyboard.  Regardless of type of keyboard, after connecting to USB adapter, the keyboard presents itself as a USB keyboard. 

The issue is thus ascribed to the specific implementation of multi-key rollover, buffering and the specific USB drivers used. 

Closing as hardware specific and unable to reproduce or write detection code in-game.

**Closed by Karsten75** 2020-06-27 16:30 UTC
Labels: bug, wontfix
