### ISSUE TITLE
[Bug] Unable to click play button on Colonies for maps on the left

### ISSUE THREAD

**Issue by GrumpyTanker** [KnuckleCracker/CW4-bug-tracker#618] opened 2021-01-11 18:04 UTC
Video of the bug in action: [https://youtu.be/zJzdXB0ESqE](https://youtu.be/zJzdXB0ESqE)

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5797507/output_log.txt)

When in the colonies screen, I'm unable to click the play button for maps on the left side. Maps on the right work fine, and I've played many of them, just any maps that show up on the left are not playable. The preview still shows up, but when I click the Play button, it closes the map.

This problem has persisted for me over the course of multiple game restarts, computer reboots, etc..

I'm running 3 monitors, so I initially thought the issue might be monitor related, but it's the same on all monitors. Also same on all monitors in fullscreen or windowed. Everything else in the game works fine, just the maps on the left side in colonies doesn't seem to work.

**Comment by knucracker** [comment] 2021-01-11 18:10
I see you are running the steam version, but you are on an old version of the game (1.0.0). Update to the current version and see if that makes a difference.  There is also a beta version you can upgrade to. Right click the game in steam, select properties. Then select betas and in the dropdown there is a "beta" you can switch to.

**Comment by GrumpyTanker** [comment] 2021-01-11 18:24
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5797603/output_log.txt)
[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5797604/Player.log)

Player log says I'm on the 1.1.2b now, still getting the same issue.

output_log.txt was last updated 12/21/2020. Don't know what's up with that.

**Comment by knucracker** [comment] 2021-01-11 18:40
The only thing 'different' I see in Player.log is that your GPU isn't a common one.  Your GPU driver dates to Oct 2020.  I'd try disabling the steam overlay for the game and see if that changes anything. Right click the game in steam and go to properties. From there you can turn off the steam overlay.

THis is not a general purpose problem (I can't reproduce it and I don't have any other reports). So there has to be something specific about your setup.  You could also try running the game in a window of different sizes, full screen, full screen exclusive. Move the window around, change the game's video settings and change them back (to see if that affect it), etc.  

Also I assume you only get this problem on the Colonies screen? Odd that it would affect the Colonies but not any other screens.

**Comment by GrumpyTanker** [comment] 2021-01-11 20:29
Yeah, it's a weird problem. Works fine on my other machines, just my ~~work~~ _other_ laptop seems to have issues. Yes, it's only the colonies screen. I've tried a lot of combinations of full/exclusive/different screens, etc.

Oh well, it doesn't affect the gameplay, just have to do some workarounds to play different colonies maps.

Love the game, keep up the good work.

**Comment by knucracker** [comment] 2021-01-12 15:07
Closing this. If more information becomes available, feel free to post it here or on a discussion topic.

**Closed by knucracker** 2021-01-12 15:07 UTC
Labels: Bug, No Fix
