### ISSUE TITLE
[Bug] Different crashes that freeze the game (singleplayer)

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#965] opened 2021-08-19 20:30 UTC
```
NullReferenceException: Object reference not set to an instance of an object.
  at UnitManager.DamageShieldCollision (System.Single extraDist) [0x00000] in <00000000000000000000000000000000>:0 
  at Spore.GameUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at GameSpace.MyFixedUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at GameSpace.Update () [0x00000] in <00000000000000000000000000000000>:0
```

```
NullReferenceException: Object reference not set to an instance of an object.
  at TerrainRangeIndicator.get_cellX () [0x00000] in <00000000000000000000000000000000>:0 
  at ShieldPanel.UpdateMesh () [0x00000] in <00000000000000000000000000000000>:0 
```

These happened in different missions, in singleplayer (not mverse) but were using custom content that spawns most things in the game (player buildings, enemy critters) using CreateUnit and CreateUnitOnTerrain so it is possible there were some bad interactions there. Unfortunately I don't have much more info than that on what exactly might've interacted wrong. High possibility of different things spawning and interacting on the same frame. I'll update the ticket if I get more information

**Comment by grabz-dev** [comment] 2021-08-20 01:54
This should probably have been labelled 4RPL, my mistake.

**Comment by knucracker** [comment] 2021-08-20 14:58
I've added some extra protection to both areas.  They both look like they might relate to a shield deploying unit being hit or damaged on the same frame they are created.  Hard to tell.  If you stumble across anything that reproduces the problem let me know.  Otherwise, I'll just include the presumptive fixes and hope for the best.

**Comment by grabz-dev** [comment] 2021-08-21 01:39
I don't have repro steps unfortunately and I'm not sure if I will be able to find any due to the nature of what is causing them.
I do come in with one more error though:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at Forb.NearDigitalis () [0x00000] in <00000000000000000000000000000000>:0 
  at Forb.GameUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at GameSpace.MyFixedUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at GameSpace.Update () [0x00000] in <00000000000000000000000000000000>:0 
```
Now just let me be clear that the crashes are rare and mainly come from some amount of stress testing we've been doing, and we've only had 1 actual gameplay crash between a few of us streaming on Discord. So the crashes at best are just very rare and probably won't happen to too many people.

**Comment by knucracker** [comment] 2021-08-24 17:39
I've added some extra protection in these Forb.NearDigitalis area as well.  Looks like it might could have thrown if the forb was outside the map for any reason.  I'll close this issue for now and it can be re-opened if necessary,

**Closed by knucracker** 2021-08-24 17:39 UTC
Labels: Bug, 4RPL, 2.2
