### ISSUE TITLE
Stacking towers at map edge

### ISSUE THREAD

**Issue by TrickyCorp** [KnuckleCracker/CW4-bug-tracker#546] opened 2020-12-24 05:39 UTC
When placing multiple soylent towers at once (click and drag), if one of them happens to be exactly next to the map edge, you can stack 2 towers on top of each other, but ONLY on the left side of the map.

I haven't tested if it can also happen at the bottom of the map (south), but it won't happen at the other 2 edges.
I haven't tested if it applies to other structures either.

Feel free to add context if you have something useful to add to this.

My guess is it's an issue with negative X and/or Z values. (north east south west)

**Comment by Karsten75** [comment] 2020-12-24 06:19
Again, save maps are invaluable in identifying and resolving issues.

**Comment by knucracker** [comment] 2020-12-24 14:58
Yeah, I have to have a save or a screenshot. I can't reproduce this based on what you describe. I place some towers that are built then attempt to drag a line of towers up the very left edge where one of them lands on an existing tower. In my test it doesn't place the unbuilt tower on the built tower.  So I must be doing something differently than you are...

**Comment by TrickyCorp** [comment] 2020-12-24 18:17
It for some reason only works if there is no tower built yet. The "stacked" tower would show it has 0 tiles (which is hard to see since the other tower at the same spot also shows the amount of tiles it can reach)

So, as a recap: dragging towers when one would get placed exactly at the map edge, and then moving the cursor past the map edge for any distance, will result in 2 unbuilt towers at the same spot.

Can I make a short youtube video where I replicate it, and link it here? I'm not always good at explaining it and pictures won't do for this time.

**Comment by Karsten75** [comment] 2020-12-24 21:49
Of course you can do a video and either upload it to here (GitHub sup[pports .mp4 uplaods) or link a YouTube video. Either will work.

**Comment by TrickyCorp** [comment] 2020-12-25 05:14
Apparently github thinks a video of less than 2 minutes is too big, so I had to link a youtube video here instead:
https://www.youtube.com/watch?v=xPKqrNFx29U

For some reason it doesn't seem to work with cannons, so I think it's a 1x1 structure only problem. I might be wrong though, so  watch the video for yourself.

**Comment by Fireswamp** [comment] 2021-04-18 00:23
You can also use this to stack towers at the edge of a cliff.  Worked with terrain differences 13 -> 1, 1 -> 13 and 12-14 -> 0; does not work with 10-12 -> 1, so it appears it requires a height difference of more than 11 so towers can't connect across the terrain height.

With a cliff it seems this is working in all directions, including diagonals.

![image](https://user-images.githubusercontent.com/68219054/115130064-3eb95980-9fba-11eb-8abf-0b31ad9c851e.png)

Drag was started at the top tower and current mouse position is bottom center of the image.

**Closed** 2022-11-08 14:43 UTC
Labels: Bug.Minor
