### ISSUE TITLE
[Bug] Build menu item out of view causes hotkey to not function

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#832] opened 2021-03-26 23:29 UTC
I was playing map #463, a map that has the forge in the struct build tab, thus making the menu scroll, when I noticed this.

Reproduce:
- Press arrow to move struct build menu down so that the tower is no longer visible.
- Try to use hotkey 1 to select the tower, which does not work.

It is expected that 1 still relates to the tower and using 1 selects the tower to build. However, nothing seems to happen as the controls are likely binded to the UI. Pressing 2 does however correctly select the pylon for building.

Build menu state for error:
![image](https://user-images.githubusercontent.com/68601223/112702064-9882a400-8e92-11eb-8d63-6a7bcd11318a.png)

**Comment by grabz-dev** [comment] 2021-03-27 01:02
Duplicate of #358

**Closed** 2022-11-13 00:55 UTC
Labels: Bug
