### ISSUE TITLE
[Bug] Colonies Tag Voting broken on map 21

### ISSUE THREAD

**Issue by Bob2Chiv** [KnuckleCracker/CW4-bug-tracker#692] opened 2021-01-31 05:57 UTC
Attempting to vote (up or down), on most maps, will leave a green or red thumb symbol in place of the white one to 'track' the vote.

On map 21 "The Wave", this is not the case, thumbing up or down on any tag will temporarily change the color but after 'retrieving' flashes, the vote will disappear. 

The vote should remain.

discord conversation if additional context is needed:
https://discord.com/channels/192420539204239361/368747848046739456/805300263186726982

**Comment by Sorrontis** [comment] 2021-01-31 06:18
I can confirm I have the same issue. 

Also would like to add. If my recollection is correct, there was a "mean" tag on this map that was either manually removed or downvoted enough to be automatically disappeared. Maybe that has something to do with it.

**Comment by knucracker** [comment] 2021-01-31 14:43
Fixed on the server (so should be working now). The problem was that voting was being treated as an "Add" and there is a max limit on the number of tags that can be applied to a map. That limit was hit, so the server was returning "-99 TAG LIMIT FOR MAP REACHED." (That should be visible in the game's log file).  I've changed it so that voting doesn't count as an "add".

**Closed by knucracker** 2021-01-31 14:43 UTC
Labels: 1.2.beta, Bug
