### ISSUE TITLE
Visual 'AC' when lowering height in mapmaker [Bug.Minor]

### ISSUE THREAD

**Issue by ProfessorOcecat** [KnuckleCracker/CW4-bug-tracker#1025] opened 2022-03-06 05:24 UTC
I looked around but I didn't see anyone else making a comment on this: 
In the mapmaker, I opened a new map 'Average' size.
I made some level 20 terrain and then reduced it to 0: the entire area was filled now with AC which vanishes as soon as I make another change to the map or if you start it. It's a little annoying so I've listed it as 'minor'.
Some images attached.
![20220306161745_1](https://user-images.githubusercontent.com/18480264/156910409-3bb4ffb2-b1ea-4acb-869d-711dc531bb6c.jpg)
![20220306161749_1](https://user-images.githubusercontent.com/18480264/156910411-0e015ede-20ec-427a-ab3b-ae8a7e533a51.jpg)
![20220306161753_1](https://user-images.githubusercontent.com/18480264/156910412-9298fc77-64e3-4285-addd-053b0e8bf457.jpg)
![20220306161614_1](https://user-images.githubusercontent.com/18480264/156910414-a3b258dd-9e19-4fbb-b908-6547ad739fac.jpg)
![20220306161723_1](https://user-images.githubusercontent.com/18480264/156910417-e4b090b9-b298-4f7d-88d1-2ce443ebeb9c.jpg)

**Comment by Bob2Chiv** [comment] 2022-05-18 15:11
Duplicate of (or at least very similar to) #586

**Closed as not planned** 2022-11-24 11:19 UTC
Labels: Bug.Minor
